spring:
  application:
    name: spring-cloud-eureka-feign-client
  config:
    import: optional:configserver:http://localhost:1111
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}