server:
  port: 1111
spring:
  profiles:
    active: native
  cloud:
    client:
      hostname: ${spring.cloud.client.ip-address:localhost}
    config:
      override-system-properties: false
      server:
        native:
          search-locations:
            classpath:/config/client-config-first